language: python
cache: pip
sudo: required
services:
  - docker
os:
  - linux
python:
  - "3.6"
script:
  - pip install -r requirements/test.txt
  - nose2 -s extractor
  - nose2
after_success:
  - coveralls
