language: python
cache: pip
sudo: required
services:
  - docker
os:
  - linux
python:
  - "3.6"
script:
  - pip install -U pip pipenv
  - pipenv install
  - pipenv run nose2 -s extractor
  - pipenv run nose2
after_success:
  - coveralls
